import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { describe, expect, test } from "vitest";
import { convertFromFile, createDefaultPipeline } from "../../src";

async function createRealPdf(targetPath: string): Promise<void> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([800, 450]);
  const font = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("Real PDF integration test", {
    x: 50,
    y: 380,
    size: 28,
    font,
    color: rgb(0.1, 0.2, 0.8)
  });

  page.drawText("Generated by pdf-lib during test runtime.", {
    x: 50,
    y: 340,
    size: 18,
    color: rgb(0.1, 0.1, 0.1)
  });

  const bytes = await pdf.save();
  await writeFile(targetPath, bytes);
}

describe("real pdf conversion", () => {
  test("converts a real generated pdf file via node adapter", async () => {
    const dir = await mkdtemp(join(tmpdir(), "p2v-real-pdf-"));
    try {
      const pdfPath = join(dir, "sample.pdf");
      await createRealPdf(pdfPath);

      const source = await readFile(pdfPath);
      const sourceInfo = await stat(pdfPath);
      expect(sourceInfo.size).toBeGreaterThan(500);
      expect(source[0]).toBe(0x25); // '%PDF'

      const pipeline = createDefaultPipeline();
      const result = await convertFromFile(
        pdfPath,
        "application/pdf",
        {
          filename: "real-pdf-converted",
          thumbnail: true,
          video: {
            fps: 30,
            frameDurationMs: 400,
            width: 1280,
            height: 720,
            format: "mp4"
          }
        },
        pipeline
      );

      expect(result.video.length).toBeGreaterThan(100);
      expect(result.thumbnail).toBeDefined();
      expect(result.metadata.frameCount).toBe(15);
      expect(result.metadata.durationMs).toBe(6000);
      expect(result.metadata.runtime).toBe("node");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
